prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix foaf: <http://xmlns.com/foaf/0.1/>

select ?name ?url
from <http://3roundstones.com/dave/me.rdf>
where{
    ?person rdfs:seeAlso ?url ;
            foaf:name ?name .
}

# arq.bat --query ex4_livefoaf.sparql